DROP DATABASE ShopManagerDB	
GO
CREATE DATABASE ShopManagerDB
GO

USE ShopManagerDB
GO

-- Product
IF OBJECT_ID('Product') IS NOT NULL
	DROP TABLE dbo.Product;
GO
CREATE TABLE Product
(
	ProductID INT IDENTITY(1, 1) PRIMARY KEY,
	CategoryID INT NOT NULL,
	ProductName NVARCHAR(100) NOT NULL DEFAULT N'Unknown',
	Price FLOAT NOT NULL DEFAULT 0
)
GO

-- ProductCategory
IF OBJECT_ID('Category') IS NOT NULL
	DROP TABLE dbo.Category;
GO
CREATE TABLE Category
(
	CategoryID INT IDENTITY(1, 1) PRIMARY KEY,
	CategoryName NVARCHAR(100) NOT NULL DEFAULT N'Unknown'
)
GO

-- Table
IF OBJECT_ID('Table') IS NOT NULL
	DROP TABLE dbo.[Table];
GO
CREATE TABLE [Table]
(
	TableID INT IDENTITY(1, 1) PRIMARY KEY,
	TableName NVARCHAR(100) NOT NULL DEFAULT N'No name',
	TableStatus NVARCHAR(10) NOT NULL DEFAULT N'Free' -- Free | Busy
)
GO

-- Account
IF OBJECT_ID('Account') IS NOT NULL
	DROP TABLE dbo.Account;
GO
CREATE TABLE Account
(
	AccountID INT IDENTITY PRIMARY KEY,
	DisplayName NVARCHAR(50) NOT NULL,
	Username NVARCHAR(50) NOT NULL,
	[Password] NVARCHAR(50) NOT NULL,
	AccountType INT NOT NULL 
)
GO

-- Bill
IF OBJECT_ID('Bill') IS NOT NULL
	DROP TABLE dbo.Bill;
GO
CREATE TABLE Bill
(
	BillID INT IDENTITY(1, 1) PRIMARY KEY,
	TableID INT NOT NULL,
	DateCheckIn DATE NOT NULL DEFAULT GETDATE(),
	DateCheckOut DATE,
	BillStatus INT NOT NULL DEFAULT 0	-- 1: paid, 0: pending
)
GO

-- BillInfo
IF OBJECT_ID('BillInfo') IS NOT NULL
	DROP TABLE dbo.BillInfo;
GO
CREATE TABLE BillInfo
(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	BillID INT NOT NULL,
	ProductID INT NOT NULL,
	Total INT NOT NULL DEFAULT 0
)
GO